# Enable mouse support
set -g mouse on

# Set default shell
set -g default-shell /usr/bin/fish

# Set status line
set -g status on

set -g status-justify centre
set -g status-style bg=black,fg=brightgreen

set -g status-left-length 50
set -g status-left " "
set -g status-right "#[fg=green,bg=black]\
	#[fg=black,bg=green] %Y-%m-%d %H:%M "

# Start tpm (keep this as last line)
#run '~/.tmux/plugins/tpm/tpm'
