# Enable mouse support
set -g mouse on

# Set status line
set -g status on
set -g status-justify centre
set -g status-style bg=black,fg=brightgreen

# Show hostname
set -g status-left-length 50
set -g status-left "#[fg=black,bg=green] #H #[fg=black,bg=green]"

# Show date and time
set -g status-right "#[fg=green,bg=black]\
	#[fg=black,bg=green] %Y-%m-%d %H:%M "
